theme = "lynx"
title = "La Cocina de Nube Rosa y Lila"

[params.author]
  name = "La Cocina de Nube Rosa y Lila"
  headline = "ğŸ‘‡ğŸ»Todas mis redes sociales aquiğŸ‘‡ğŸ»"
  image = "https://yt3.googleusercontent.com/sQvWLP7KQZt1_9LUYP6_NQo6SdWmcNsXMiS-C4MpfHvMNoBcrmiloV_Pxe6NI0OkCKq_lazS=s900-c-k-c0x00ffffff-no-rj"

links = [
  { link = { href = "https://www.youtube.com/@LaCocinadeNubeRosayLila", text = "Youtube", icon = "youtube"} },
  { link = { href = "https://www.instagram.com/lacocinadenuberosaylila/?locale=es&hl=es", text = "Instagram", icon = "instagram"} },
  { link = { href = "https://www.tiktok.com/@lacocinadenuberosaylila", text = "Tiktok", icon = "tiktok"} },
  { link = { href = "https://www.facebook.com/sonianube.rosa/", text = "Facebook", icon = "facebook"} }
]

